import = [
    "~/.config/alacritty/themes/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 11

[font.bold]
family = "JetBrainsMono NF"

[font.bold_italic]
family = "JetBrainsMono NF"

[font.italic]
family = "JetBrainsMono NF"

[font.normal]
family = "JetBrainsMono NF"
