font:
  size: 13
  normal:
    family: 'JetBrainsMono NF'
  bold:
    family: 'JetBrainsMono NF'
  italic:
    family: 'JetBrainsMono NF'
  bold_italic:
    family: 'JetBrainsMono NF'

env:
  TERM: xterm-256color
